### ISSUE TITLE
Dev UI Tweaks

### ISSUE THREAD

**Issue by danielattilasimon** [liquity/dev#346]
These are the remaining tasks to get Dev UI launch-ready in decreasing order of priority. We can use this issue to tweak priorities / add items before we create sub-issues for each.

- [x] Add kickback rate to stats panel
- [x] Add APY estimation to Farm panel
- [x] Add APY estimation to Stability Pool panel
- [x] Add headings and modifications to Liquity stats panel
~~- [ ] Add APY estimation to Staking panel~~
- [x] Add Close Trove button to Trove panel
- [x] Update app copy from copy doc
- [ ] Show value of LQTY and LUSD in Stats panel 
- [ ] Preserve local form state when navigating
- [x] Add LQTY and LUSD icons to devui repo
- [x] Lock down package.json dependencies
- [x] [Add render states and CTAs to Stability panel](https://github.com/liquity/dev/issues/345)
- [x] [Add render states and CTAs to Stake panel](https://github.com/liquity/dev/issues/347)
- [x] Add render states and CTAs to Redemption panel (does it have multiple states?)
- [x] Add liquidation reserve row to trove panel
- [x] Trove panel: Move action description out of CTA button onto row above the buttons
- [x] Unipool staking and reward claiming 
- [x] All panels: Move pre-flight check error message out of CTA button onto row above the buttons
- [x] Add max buttons to input fields
- [x] Add info icons to panels #419
- [x] Add TVL in ETH and USD to stats #412
- [x] Move stats into own page
- [x] Move liquidate into own page
- [x] Move redemption into own page (?)

- [x] Risky troves panel incorrectly shows Troves as not liquidatable #402
